version: "3.9"
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    volumes:
      - ./minio/data:/data

  spark:
    build: ./spark
    container_name: spark
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
      S3_ENDPOINT: http://minio:9000
      PYSPARK_PYTHON: python3
    volumes:
      - ./notebooks:/opt/workspace/notebooks
    command: >
      bash -c "
      start.sh jupyter notebook
        --ip=0.0.0.0
        --port=8888
        --allow-root
        --NotebookApp.token=''
        --NotebookApp.password=''
      "

  postgis:
    image: postgis/postgis:15-3.3-alpine
    platform: linux/amd64
    container_name: postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evlake
    ports:
    - "5433:5432"